apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    fdk.service: fdk-reports-store
  name: fdk-reports-store
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    fdk.service: fdk-reports-store
status:
  loadBalancer: {}